name: Build CLI

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.9
          bundler-cache: true

      - name: Install bashly
        run: |
          gem install psych
          gem install bashly

      - name: Generate CLI
        run: bashly generate

  #    - name: Commit generated script
  #        git config --global user.name "github-actions[bot]"
  #      run: |
  #        git config --global user.email "github-actions[bot]@users.noreply.github.com"
  #        git add kibana-rules-export
  #        git commit -m "Auto-compiled CLI with bashly" || echo "Nothing to commit"
  #        git push origin HEAD:main
